<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Dtos\" />
    <Folder Include="Dtos\CustomerType\" />
    <Folder Include="Dtos\Customer\" />
    <Folder Include="Entities\" />
    <Folder Include="Entities\Common\" />
    <Folder Include="Helpers\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Mappings\" />
    <Folder Include="MisaAttributes\" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

</Project>
